### ISSUE TITLE
CSV import issue

### ISSUE THREAD

**Issue by groundnation** [littlegiant/silverstripe-seo-editor#2]
Great module. I am experiencing an issue importing a CSV file - get "Nothing to import" message after importing.

**Comment by stevie-mayhew** [comment]
Hi @groundnation - thanks for the issue. Do you have an example of the CSV you are trying to import?

**Comment by groundnation** [comment]
Hi Stevie - here you go...

https://www.dropbox.com/s/yojc65rrf908cin/test.csv?dl=0

**Comment by groundnation** [comment]
Hi Stevie - seems the data is in fact getting imported, so apologies for raising this, but the "Nothing to import" message is just a bit misleading as this is shown when data has been imported..

**Comment by stevie-mayhew** [comment]
Sorry about the slow response @groundnation! I'll have a look at the messaging today
